apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb
  namespace: default
spec:
  interval: 60m
  releaseName: kubedb
  targetNamespace: kubedb
  storageNamespace: kubedb
  install:
    createNamespace: true
  chart:
    spec:
      chart: kubedb
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: appscode-oci
        namespace: default
