apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hello-oci
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  values:
    data:
      a: "100"
      b: "5"
