apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-oci.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $k, $v := .Values.data }}
  {{- if $v }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}
